AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Deployment of NVA from SAR

Parameters:
  CognitoAuthorizerArn:
    Type: String
    Description: Reference to Cognito UserPool for the stage
    Default: arn:aws:cognito-idp:eu-west-1:812481234721:userpool/eu-west-1_wsHsxCiT4
  AmazonCognitoDomain:
    Type: String
    Description: URL to the the sign-up and sign-in pages that are hosted by Amazon Cognito
    Default: https://nva-test.auth.eu-west-1.amazoncognito.com
  BackendDomain:
    Type: String
    Description: Domainname for the backend api
    Default: api.test.nva.aws.unit.no
  CognitoIdentityPoolId:
    Type: String
    Description: Identifier of the IdentityPool assosiated with the UserPool
    Default: eu-west-1:c1187e43-cbb7-401f-8181-9c94d8e94b6a
  DomainCertificateArn:
    Type: String
    Description: ARN  of certificate to assign to the assosiated Domain
    Default: arn:aws:acm:us-east-1:812481234721:certificate/9319e9f9-3a66-43bb-9f9c-7fc1e6b4d3ab
  FrontendDomain:
    Type: String
    Description: Domainname to distribute the fronted application onto
    Default: frontend.test.nva.aws.unit.no
  RedirectSignInUrl:
    Type: String
    Default: https://frontend.test.nva.aws.unit.no/login
  RedirectSignOutUrl:
    Type: String
    Default: https://frontend.test.nva.aws.unit.no/logout
  UserPoolAppClientId:
    Type: String
    Description: Identifier to use for the app clients to access this user pool
    Default: 77136duraj3vml8mi38j1hlhmv
  UserPoolId:
    Type: String
    Description: Identifier of the UserPool in Cognito
    Default: eu-west-1_wsHsxCiT4
  BareApiKey:
    Type: String
    Description: Key to access bare
    NoEcho: true
    Default: '{{resolve:secretsmanager:bareApiKey:SecretString}}'
  BareHost:
    Type: String
    Description: Address to bare
    Default: alfa-a.bibsys.no
  AlmaSruHost:
    Type: String
    Description: Address to Alma-SRU
    Default: bibsys.alma.exlibrisgroup.com/view/sru/47BIBSYS_NETWORK
  OrcidBaseUrl:
    Type: String
    Description: Address to ORCID services
    Default: https://sandbox.orcid.org
  OrcidClientID:
    Type: String
    Description: Clientid for ORCID
    Default: APP-QHBJSU99SZV1LMQJ
  OrcidClientSecret:
    Type: String
    Description: Secret to authenticate for ORCID
    NoEcho: true
    Default: '{{resolve:secretsmanager:REACT_APP_ORCID_CLIENT_SECRET:SecretString}}'
  OrcidRedirectUri:
    Type: String
    Description: RedirectUrl after login to ORCID
    Default: https://frontend.test.nva.aws.unit.no/user
  AlmaApiUrl:
    Type: String
    Description: URL to ALMA Library services
    Default: https://bibsys.alma.exlibrisgroup.com/view/sru/47BIBSYS_NETWORK



Resources:
  NVAFrontend:
    Type: AWS::Serverless::Application
    Description: NVA Frontend
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:eu-west-1:884807050265:applications/NVA-Frontend
        SemanticVersion: 1.1.2
      Parameters:
        AlmaApiUrl: !Ref AlmaSruHost
        AmazonCognitoDomain: !Ref AmazonCognitoDomain
        FrontendDomain: !Ref FrontendDomain
        BackendDomain: !Ref BackendDomain
        DomainCertificateArn: !Ref DomainCertificateArn
        CognitoIdentityPoolId: !Ref CognitoIdentityPoolId
        UserPoolId: !Ref UserPoolId
        UserPoolAppClientId: !Ref UserPoolAppClientId
        RedirectSignInUrl: !Ref RedirectSignInUrl
        RedirectSignOutUrl: !Ref RedirectSignOutUrl
        OrcidBaseUrl: !Ref OrcidBaseUrl
        OrcidClientID: !Ref OrcidClientID
        OrcidClientSecret: !Ref OrcidClientSecret
        OrcidRedirectUri: !Ref OrcidRedirectUri

  BackendLambdas:
    Type: AWS::CloudFormation::Stack
    Description: Backend lambdas
    Properties:
      TemplateURL: !Sub "https://nva-infrastructure-test.s3-eu-west-1.amazonaws.com/deploy_backend.yml"
      Parameters:
        CognitoAuthorizerArn: !Ref CognitoAuthorizerArn
        BackendDomain: !Ref BackendDomain
        BareApiKey: !Ref BareApiKey
        BareHost: !Ref BareHost
        AlmaSruHost: !Ref AlmaSruHost

