AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Deployment of NVA from SAR

Parameters:
  CognitoAuthorizerArn:
    Type: String
    Description: Reference to Cognito UserPool for the stage
    Default: arn:aws:cognito-idp:eu-west-1:812481234721:userpool/eu-west-1_wsHsxCiT4
  BackendDomain:
    Type: String
    Description: Domainname for the backend api
    Default: api.test.nva.aws.unit.no
  BareApiKey:
    Type: String
    Description: Key to access bare
    NoEcho: true
    Default: '{{resolve:secretsmanager:bareApiKey:SecretString}}'
  BareHost:
    Type: String
    Description: Address to bare
    Default: alfa-a.bibsys.no
  AlmaSruHost:
    Type: String
    Description: Address to Alma-SRU
    Default: bibsys.alma.exlibrisgroup.com/view/sru/47BIBSYS_NETWORK

Resources:

  SruLastPublication:  # nva-alma-proxy
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:eu-west-1:884807050265:applications/SruLastPublication
        SemanticVersion: 1.0.0
      Parameters:
        CognitoAuthorizerArn: !Ref CognitoAuthorizerArn
        CustomDomain: !Ref BackendDomain
        CustomDomainBasePath: alma
        AlmaSruHost: !Ref AlmaSruHost

  NvaDoiTransformer: # nva-doi-transformer
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:eu-west-1:884807050265:applications/NvaDoiTransformer
        SemanticVersion: 1.0.0
      Parameters:
        CognitoAuthorizerArn: !Ref CognitoAuthorizerArn
        CustomDomain: !Ref BackendDomain
        CustomDomainBasePath: doi-transform

  ResourceApi: # nva-resource-api
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:eu-west-1:884807050265:applications/ResourceApi
        SemanticVersion: 1.0.0
      Parameters:
        CognitoAuthorizerArn: !Ref CognitoAuthorizerArn
        CustomDomain: !Ref BackendDomain
        CustomDomainBasePath: resource
        # Reference to table containing resource data - refer to template?
        ResourceTable: nva_resources

  UploadMultipart: # nva-upload-multipart
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:eu-west-1:884807050265:applications/UploadMultipart
        SemanticVersion: 1.0.0
      Parameters:
        CognitoAuthorizerArn: !Ref CognitoAuthorizerArn
        CustomDomain: !Ref BackendDomain
        CustomDomainBasePath: upload
        S3UploadBucket: nva-storage-test # S3 Bucket to upload files to  - refer to template?

  PersonData:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:eu-west-1:884807050265:applications/PersonData
        SemanticVersion: 1.0.0
      Parameters:
        BareApiKey: '{{resolve:secretsmanager:bareApiKey:SecretString}}'
        BareHost: !Ref BareHost
        CognitoAuthorizerArn: !Ref CognitoAuthorizerArn
        CustomDomain: !Ref BackendDomain
        CustomDomainBasePath: person

  NvaPublicationApi: # nva-publication-api
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:eu-west-1:884807050265:applications/NvaPublicationApi
        SemanticVersion: 1.0.0
      Parameters:
        CognitoAuthorizerArn: !Ref CognitoAuthorizerArn
        CustomDomainBasePath: publication
        CustomDomain: !Ref BackendDomain

  PublicationChannelRegister: # nva-channel-registry
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:eu-west-1:884807050265:applications/PublicationChannelRegister
        SemanticVersion: 1.0.0
      Parameters:
        CognitoAuthorizerArn: !Ref CognitoAuthorizerArn
        CustomDomain: !Ref BackendDomain
        CustomDomainBasePath: publication-channel

  Institutions: # nva-cristin-institutions
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:eu-west-1:884807050265:applications/Institutions
        SemanticVersion: 1.0.0
      Parameters:
        CognitoAuthorizerArn: !Ref CognitoAuthorizerArn
        CustomDomain: !Ref BackendDomain
        CustomDomainBasePath: institution

  nvafetchdoi: # nva-fetch-doi
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:eu-west-1:884807050265:applications/nva-fetch-doi
        SemanticVersion: 1.0.0
      Parameters:
        CognitoAuthorizerArn: !Ref CognitoAuthorizerArn
        CustomDomain: !Ref BackendDomain
        CustomDomainBasePath: doi-fetch

  Projects: # nva-cristin-projects
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:eu-west-1:884807050265:applications/Projects
        SemanticVersion: 1.0.0
      Parameters:
        CognitoAuthorizerArn: !Ref CognitoAuthorizerArn
        CustomDomain: !Ref BackendDomain
        CustomDomainBasePath: project

  NVADOIProxy: # nva-doi-lambda
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:eu-west-1:884807050265:applications/NVA-DOI-Proxy
        SemanticVersion: 1.0.0
      Parameters:
        CognitoAuthorizerArn: !Ref CognitoAuthorizerArn
        CustomDomain: !Ref BackendDomain
        CustomDomainBasePath: doi
