AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: Setup an hostedzone/domain


Parameters:


  DomainCerificate:
    Type: String
    Description: ARN of certificate to cover domains


Resources:

#  HostedZoneCertificate:
#    Type: AWS::CertificateManager::Certificate
#    Properties:
#      DomainName: String
#      DomainValidationOptions:
#        - DomainValidationOption
#      SubjectAlternativeNames:
#        - String
#      Tags:
#        - Tag
#      ValidationMethod: String
#
#  HostedZone:
#    Type: AWS::Route53::HostedZone
#    Properties:
#      HostedZoneConfig:
#        HostedZoneConfig
#      HostedZoneTags:
#        - HostedZoneTag
#      Name: String
#      QueryLoggingConfig:
#        QueryLoggingConfig
#      VPCs:
#        - VPC

  FrontendDomain:
    Type: AWS::ApiGateway::DomainName
    Properties:
      CertificateArn: !Ref DomainCerificate
      DomainName: 'frontend'

  AuthDomain:
    Type: AWS::ApiGateway::DomainName
    Properties:
      CertificateArn: !Ref DomainCerificate
      DomainName: 'auth'

  BackendApiDomain:
    Type: AWS::ApiGateway::DomainName
    Properties:
      CertificateArn: !Ref DomainCerificate
      DomainName: 'api'

Outputs:
  FrontendDomain:
    Description: Domain assigned to the frontend
    Value: !Ref FrontendDomain
  AuthDomain:
    Description: Domain assigned the Cognito login
    Value: !Ref AuthDomain
  BackendApiDomain:
    Description: Domain assigned to the backend API
    Value: !Ref BackendApiDomain

