AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: Setup S3 Bucket for NVA file storage for test account



Resources:

  NVAStorageBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: nva-storage-test
      CorsConfiguration:
        CorsRules:
        - AllowedHeaders: ['*']
          AllowedMethods: [GET, PUT, POST, HEAD]
          AllowedOrigins: ['*']
          ExposedHeaders: [ETag]
      LifecycleConfiguration:
        Rules:
          - Id: RemoveFailedUploads
            Status: Enabled
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 7
      VersioningConfiguration:
        Status: Enabled


  NVAStorageBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref NVAStorageBucket
      PolicyDocument:
        Statement:
          - Action:
            - "s3:GetObject"
            - "s3:PutObject"
            - "s3:AbortMultipartUpload"
            - "s3:ListMultipartUploadParts"
            - "s3:ListBucketMultipartUploads"
            Effect: "Allow"
            Resource:
              - arn:aws:s3:::nva-storage-test
              - arn:aws:s3:::nva-storage-test/*
            Principal:
              Service:
                - lambda.amazonaws.com
